settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: tanzhen # unique identifier
    name: 探针
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.511666.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  
  - id: alist
    name: Alist
    url: 'https://www.1kb.lol/'
    method: GET
    expectStatus: 200
    
  - id: memos
    name: Memos
    description: 'Built for anything connected to the Internet.'
    url: 'https://oimio.lol/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: bitwarden
    name: 密码库
    url: 'https://1mb.lol/'
    method: GET
    expectStatus: 200
    
  - id: bitwarden
    name: OneDrive E5
    url: 'https://1tb.lol/'
    method: GET
    expectStatus: 200
    
  - id: dujiaoshuka
    name: 独角发卡
    url: 'https://shop.1tb.lol/'
    method: GET
    expectStatus: 200
    
  - id: qinglong
    name: 青龙
    url: 'https://ql.1kb.lol/'
    method: GET
    expectStatus: 200
